root: true
overrides:
  - files:
      - "*.js"
    env:
      es2020: true # first version to support lookbehind with regexp
      node: true # so that "module" is defined
      browser: true # so that "window" is defined
    extends:
      - eslint:recommended
      - prettier # this turns off all rules from eslint, @typescript-eslint and @angular-eslint that conflicts with prettier
    rules:
      dot-notation: error
      eqeqeq:
        - error
        - smart
      guard-for-in: error
      max-lines:
        - error
        - max: 300
      max-lines-per-function:
        - error
        - max: 35
      no-bitwise: error
      no-caller: error
      no-console:
        - error
        - allow:
            - info
            - warn
            - error
      no-else-return: error
      no-eval: error
      no-new-wrappers: error
      no-sequences: error
      no-throw-literal: error
      no-undef-init: error
      no-unused-expressions: error
      no-useless-concat: error
      no-useless-escape: error
      object-shorthand: error
      prefer-exponentiation-operator: error
      prefer-object-spread: error
      prefer-regex-literals: error
      prefer-template: error
      radix: error
      sort-imports:
        - error
        - ignoreDeclarationSort: true
      spaced-comment: error
      id-length: off
      no-param-reassign: off
      prefer-rest-params: off
      no-underscore-dangle: off
  - files:
      - "*.ts"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project:
        - tsconfig.json
      createDefaultProgram: true
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/eslint-plugin/recommended
      - plugin:@angular-eslint/all
      - plugin:@angular-eslint/template/process-inline-templates
      - prettier # this turns off all rules from eslint, @typescript-eslint and @angular-eslint that conflicts with prettier
    rules:
      # deactivate unwanted rules
      "@angular-eslint/prefer-on-push-component-change-detection": off
      "@angular-eslint/sort-ngmodule-metadata-arrays": off # preferred order is 'imports', 'declarations', 'providers'
      "@angular-eslint/use-component-view-encapsulation": off # oblique uses ViewEncapsulation.NONE
      "@angular-eslint/use-injectable-provided-in": off # some specialized services are directly provided in a component

      # override default values
      "@angular-eslint/no-host-metadata-property":
        - error
        - allowStatic: true

      # rules that need some refactoring to be enabled
      "@angular-eslint/component-max-inline-declarations": off

      # other rules that will be processed later
      "@typescript-eslint/member-ordering":
        - error
        - default:
            - public-static-field
            - public-instance-field
            - protected-static-field
            - protected-instance-field
            - private-static-field
            - private-instance-field
            - public-constructor
            - protected-constructor
            - private-constructor
            - public-static-method
            - public-instance-method
            - protected-static-method
            - protected-instance-method
            - private-static-method
            - private-instance-method
      "@typescript-eslint/array-type": error
      "@typescript-eslint/ban-tslint-comment": error
      "@typescript-eslint/consistent-type-assertions": error
      "@typescript-eslint/default-param-last": error
      "@typescript-eslint/method-signature-style": error
      "@typescript-eslint/no-duplicate-imports": error
      "@typescript-eslint/no-floating-promises": error
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": error
      "@typescript-eslint/no-unnecessary-type-assertion": error
      "@typescript-eslint/prefer-includes": error
      "@typescript-eslint/prefer-optional-chain": error
      "@typescript-eslint/prefer-readonly": error
      "@typescript-eslint/prefer-regexp-exec": error
      "@typescript-eslint/prefer-string-starts-ends-with": error
      "@typescript-eslint/unified-signatures": error
      dot-notation: error
      eqeqeq:
        - error
        - smart
      guard-for-in: error
      max-lines:
        - error
        - max: 300
      max-lines-per-function:
        - error
        - max: 35
      no-bitwise: error
      no-caller: error
      no-console:
        - error
        - allow:
            - info
            - warn
            - error
      no-else-return: error
      no-eval: error
      no-new-wrappers: error
      no-sequences: error
      no-throw-literal: error
      no-undef-init: error
      no-unused-expressions: error
      no-useless-concat: error
      no-useless-escape: error
      object-shorthand: error
      prefer-exponentiation-operator: error
      prefer-object-spread: error
      prefer-regex-literals: error
      prefer-template: error
      radix: error
      sort-imports:
        - error
        - ignoreDeclarationSort: true
      spaced-comment: error
      id-length: off
      no-param-reassign: off
      prefer-rest-params: off
      no-underscore-dangle: off
      "@typescript-eslint/no-explicit-any": off
      "@typescript-eslint/explicit-module-boundary-types": off
      "@typescript-eslint/ban-types": off
      "@typescript-eslint/no-var-requires": off
      "@typescript-eslint/explicit-function-return-type": off
      "@typescript-eslint/no-unsafe-member-access": off
      "@typescript-eslint/no-unsafe-assignment": off
      "@typescript-eslint/no-use-before-define": off
      "@typescript-eslint/restrict-template-expressions": off
      "@typescript-eslint/no-unused-expressions": off
      "@typescript-eslint/no-base-to-string": off
      "@typescript-eslint/restrict-plus-operands": off
      "@typescript-eslint/no-shadow": off
  - files:
      - mock-*.ts
    rules:
      "@typescript-eslint/no-unused-vars": off
      "@typescript-eslint/no-empty-function": off
  - files:
      - "*.spec.ts"
    rules:
      "@typescript-eslint/ban-ts-comment": off
      "@typescript-eslint/no-floating-promises": off
      "@angular-eslint/use-component-selector": off
      max-lines-per-function: off
      max-lines: off
  - files:
      - "schematics/**/*.ts"
    rules:
      max-lines: off
      max-lines-per-function: off
  - files:
      - "*.decorator.ts"
    rules:
      max-lines-per-function: off
  - files:
      - polyfills.ts
    rules:
      spaced-comment: off
  - files:
      - "*.html"
    extends:
      - plugin:@angular-eslint/template/recommended
