extends: "../.eslintrc.yml"
ignorePatterns:
  - "!**/*"
overrides:
  - files:
    - "*.ts"
    parserOptions:
      project:
      - src/tsconfig.app.json
      - src/tsconfig.spec.json
    rules:
      "@angular-eslint/directive-selector":
      - error
      - type: attribute
        prefix: sc
        style: camelCase
      "@angular-eslint/component-selector":
      - error
      - type: element
        prefix: sc
        style: kebab-case
